Add 'use client' directive to PageContainerContext
PageContainerContext uses createContext which requires the file to be
a Client Component in App Router. This was causing a server error when
navigating to journey pages.

Error: createContext only works in Client Components